version: "3.8"

services:
  app:
    build: .
    container_name: bank-merchant-api
    ports:
      - "8080:8080"
    env_file:
      - .env # Load environment variables from .env file
    environment:
      TZ: Asia/Jakarta # Set time zone
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
